#encoding:utf-8
# mysql 配置
# SQLALCHEMY_DATABASE_URI  = 'mysql://root:123456@127.0.0.1/mysql'
# SQLALCHEMY_TRACK_MODIFICATIONS = False
# SERVER_PORT = 8999
# DEBUG = False
# SQLALCHRMY_ECHO = False


SQLALCHEMY_DATABASE_URI  = 'mysql://root:123456@127.0.0.1/mysql'
SQLALCHEMY_TRACK_MODIFICATIONS = False
DEBUG = True
SQLALCHRMY_ECHO = True
SQLALCHRMY_ENCODING = 'utf-8'
SERVER_PORT = 9000

